### ISSUE TITLE
Known issue: Top 10 student. Same grade, same position

### ISSUE THREAD

**Issue by christianemardaniag** [christianemardaniag/Grading-Management-System#5]
Dapat pag multiple ung mag kakaparehas na grade for top student dapat nasa isang number lang sila.
Ex. Tatlo ung naka kuha ng 1.0 na same din ng grade value na 100. Dapat pare-parehas silang top 1.
Tapos kukuha pa din ng top 2 and top 3

**Comment by trese24** [comment]
Good day sir! pwede ko ba gamitin ung grading management system nyo sir? as a permission sa owner po sainyo hehe

**Comment by christianemardaniag** [comment]
Saan mo gagamitin ung project? 

> Good day sir! pwede ko ba gamitin ung grading management system nyo sir? as a permission sa owner po sainyo hehe

Saan mo gagamitin ung project?
